import { SalesRecord } from "../service/revenueTrends/revenueTrends.service";

const SampleData: SalesRecord[] = [
    {
        "date": "15-01-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 5,
        "unitPrice": 299.99,
        "totalRevenue": 1499.95,
        "customerType": "B2B",
        "customerName": "TechCorp Solutions"
    },
    {
        "date": "18-01-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 2,
        "unitPrice": 1299.99,
        "totalRevenue": 2599.98,
        "customerType": "B2B",
        "customerName": "DataFlow Inc"
    },
    {
        "date": "22-01-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 3,
        "unitPrice": 599.99,
        "totalRevenue": 1799.97,
        "customerType": "B2B",
        "customerName": "Innovation Labs"
    },
    {
        "date": "25-01-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 1,
        "unitPrice": 2499.99,
        "totalRevenue": 2499.99,
        "customerType": "B2B",
        "customerName": "StartupCo"
    },
    {
        "date": "28-01-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 8,
        "unitPrice": 299.99,
        "totalRevenue": 2399.92,
        "customerType": "B2B",
        "customerName": "Global Manufacturing"
    },
    {
        "date": "02-02-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 4,
        "unitPrice": 899.99,
        "totalRevenue": 3599.96,
        "customerType": "B2B",
        "customerName": "Design Studio Pro"
    },
    {
        "date": "05-02-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 6,
        "unitPrice": 199.99,
        "totalRevenue": 1199.94,
        "customerType": "B2C",
        "customerName": "Individual Customer"
    },
    {
        "date": "08-02-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 12,
        "unitPrice": 299.99,
        "totalRevenue": 3599.88,
        "customerType": "B2B",
        "customerName": "Regional Bank Corp"
    },
    {
        "date": "12-02-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Consulting",
        "productName": "Training Package",
        "quantity": 2,
        "unitPrice": 999.99,
        "totalRevenue": 1999.98,
        "customerType": "B2B",
        "customerName": "Tech Academy"
    },
    {
        "date": "15-02-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 7,
        "unitPrice": 599.99,
        "totalRevenue": 4199.93,
        "customerType": "B2B",
        "customerName": "Research Institute"
    },
    {
        "date": "18-02-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 3,
        "unitPrice": 1299.99,
        "totalRevenue": 3899.97,
        "customerType": "B2B",
        "customerName": "Cloud Hosting Co"
    },
    {
        "date": "22-02-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 15,
        "unitPrice": 199.99,
        "totalRevenue": 2999.85,
        "customerType": "B2B",
        "customerName": "Financial Services Ltd"
    },
    {
        "date": "25-02-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 4,
        "unitPrice": 299.99,
        "totalRevenue": 1199.96,
        "customerType": "B2B",
        "customerName": "Marketing Agency"
    },
    {
        "date": "28-02-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Strategy Consulting",
        "quantity": 1,
        "unitPrice": 4999.99,
        "totalRevenue": 4999.99,
        "customerType": "B2B",
        "customerName": "Enterprise Corp"
    },
    {
        "date": "05-03-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 6,
        "unitPrice": 899.99,
        "totalRevenue": 5399.94,
        "customerType": "B2B",
        "customerName": "Architecture Firm"
    },
    {
        "date": "08-03-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 9,
        "unitPrice": 599.99,
        "totalRevenue": 5399.91,
        "customerType": "B2B",
        "customerName": "E-commerce Giant"
    },
    {
        "date": "12-03-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 20,
        "unitPrice": 199.99,
        "totalRevenue": 3999.8,
        "customerType": "B2B",
        "customerName": "Government Agency"
    },
    {
        "date": "15-03-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 18,
        "unitPrice": 299.99,
        "totalRevenue": 5399.82,
        "customerType": "B2B",
        "customerName": "Healthcare Network"
    },
    {
        "date": "18-03-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 1,
        "unitPrice": 1299.99,
        "totalRevenue": 1299.99,
        "customerType": "B2B",
        "customerName": "Startup Hub"
    },
    {
        "date": "22-03-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 3,
        "unitPrice": 2499.99,
        "totalRevenue": 7499.97,
        "customerType": "B2B",
        "customerName": "Manufacturing Corp"
    },
    {
        "date": "25-03-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 11,
        "unitPrice": 599.99,
        "totalRevenue": 6599.89,
        "customerType": "B2B",
        "customerName": "Retail Chain"
    },
    {
        "date": "28-03-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 8,
        "unitPrice": 199.99,
        "totalRevenue": 1599.92,
        "customerType": "B2C",
        "customerName": "Individual Customer"
    },
    {
        "date": "02-04-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 14,
        "unitPrice": 299.99,
        "totalRevenue": 4199.86,
        "customerType": "B2B",
        "customerName": "Logistics Company"
    },
    {
        "date": "05-04-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 5,
        "unitPrice": 899.99,
        "totalRevenue": 4499.95,
        "customerType": "B2B",
        "customerName": "Creative Agency"
    },
    {
        "date": "08-04-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 25,
        "unitPrice": 199.99,
        "totalRevenue": 4999.75,
        "customerType": "B2B",
        "customerName": "Insurance Group"
    },
    {
        "date": "12-04-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Consulting",
        "productName": "Training Package",
        "quantity": 4,
        "unitPrice": 999.99,
        "totalRevenue": 3999.96,
        "customerType": "B2B",
        "customerName": "University System"
    },
    {
        "date": "15-04-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 13,
        "unitPrice": 599.99,
        "totalRevenue": 7799.87,
        "customerType": "B2B",
        "customerName": "Consulting Firm"
    },
    {
        "date": "18-04-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 2,
        "unitPrice": 1299.99,
        "totalRevenue": 2599.98,
        "customerType": "B2B",
        "customerName": "Tech Startup"
    },
    {
        "date": "22-04-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 16,
        "unitPrice": 299.99,
        "totalRevenue": 4799.84,
        "customerType": "B2B",
        "customerName": "Real Estate Group"
    },
    {
        "date": "25-04-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 12,
        "unitPrice": 199.99,
        "totalRevenue": 2399.88,
        "customerType": "B2B",
        "customerName": "Fintech Company"
    },
    {
        "date": "28-04-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Consulting",
        "productName": "Strategy Consulting",
        "quantity": 2,
        "unitPrice": 4999.99,
        "totalRevenue": 9999.98,
        "customerType": "B2B",
        "customerName": "Multinational Corp"
    },
    {
        "date": "02-05-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 8,
        "unitPrice": 599.99,
        "totalRevenue": 4799.92,
        "customerType": "B2B",
        "customerName": "Media Company"
    },
    {
        "date": "05-05-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 7,
        "unitPrice": 899.99,
        "totalRevenue": 6299.93,
        "customerType": "B2B",
        "customerName": "Game Development Studio"
    },
    {
        "date": "08-05-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 22,
        "unitPrice": 299.99,
        "totalRevenue": 6599.78,
        "customerType": "B2B",
        "customerName": "Non-profit Org"
    },
    {
        "date": "12-05-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 18,
        "unitPrice": 199.99,
        "totalRevenue": 3599.82,
        "customerType": "B2B",
        "customerName": "Legal Firm"
    },
    {
        "date": "15-05-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 4,
        "unitPrice": 1299.99,
        "totalRevenue": 5199.96,
        "customerType": "B2B",
        "customerName": "Data Center Co"
    },
    {
        "date": "18-05-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 2,
        "unitPrice": 2499.99,
        "totalRevenue": 4999.98,
        "customerType": "B2B",
        "customerName": "Enterprise Solutions"
    },
    {
        "date": "22-05-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 15,
        "unitPrice": 599.99,
        "totalRevenue": 8999.85,
        "customerType": "B2B",
        "customerName": "Market Research Co"
    },
    {
        "date": "25-05-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 20,
        "unitPrice": 299.99,
        "totalRevenue": 5999.8,
        "customerType": "B2B",
        "customerName": "Sales Organization"
    },
    {
        "date": "28-05-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 30,
        "unitPrice": 199.99,
        "totalRevenue": 5999.7,
        "customerType": "B2B",
        "customerName": "Cybersecurity Firm"
    },
    {
        "date": "02-06-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 3,
        "unitPrice": 899.99,
        "totalRevenue": 2699.97,
        "customerType": "B2C",
        "customerName": "Individual Customer"
    },
    {
        "date": "05-06-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Training Package",
        "quantity": 6,
        "unitPrice": 999.99,
        "totalRevenue": 5999.94,
        "customerType": "B2B",
        "customerName": "Training Institute"
    },
    {
        "date": "08-06-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 10,
        "unitPrice": 599.99,
        "totalRevenue": 5999.9,
        "customerType": "B2B",
        "customerName": "Analytics Company"
    },
    {
        "date": "12-06-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 28,
        "unitPrice": 299.99,
        "totalRevenue": 8399.72,
        "customerType": "B2B",
        "customerName": "Enterprise Software Co"
    },
    {
        "date": "15-06-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 22,
        "unitPrice": 199.99,
        "totalRevenue": 4399.78,
        "customerType": "B2B",
        "customerName": "Security Consultancy"
    },
    {
        "date": "18-06-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 5,
        "unitPrice": 1299.99,
        "totalRevenue": 6499.95,
        "customerType": "B2B",
        "customerName": "Cloud Provider"
    },
    {
        "date": "22-06-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Consulting",
        "productName": "Strategy Consulting",
        "quantity": 1,
        "unitPrice": 4999.99,
        "totalRevenue": 4999.99,
        "customerType": "B2B",
        "customerName": "Growth Company"
    },
    {
        "date": "25-06-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 17,
        "unitPrice": 599.99,
        "totalRevenue": 10199.83,
        "customerType": "B2B",
        "customerName": "Business Intelligence Co"
    },
    {
        "date": "28-06-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 24,
        "unitPrice": 299.99,
        "totalRevenue": 7199.76,
        "customerType": "B2B",
        "customerName": "Customer Success Co"
    },
    {
        "date": "02-07-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 8,
        "unitPrice": 899.99,
        "totalRevenue": 7199.92,
        "customerType": "B2B",
        "customerName": "Design Consultancy"
    },
    {
        "date": "05-07-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 35,
        "unitPrice": 199.99,
        "totalRevenue": 6999.65,
        "customerType": "B2B",
        "customerName": "Security Provider"
    },
    {
        "date": "08-07-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 19,
        "unitPrice": 299.99,
        "totalRevenue": 5699.81,
        "customerType": "B2B",
        "customerName": "Marketing Platform"
    },
    {
        "date": "12-07-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 4,
        "unitPrice": 2499.99,
        "totalRevenue": 9999.96,
        "customerType": "B2B",
        "customerName": "Digital Transformation Co"
    },
    {
        "date": "15-07-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 21,
        "unitPrice": 599.99,
        "totalRevenue": 12599.79,
        "customerType": "B2B",
        "customerName": "Data Science Company"
    },
    {
        "date": "18-07-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 3,
        "unitPrice": 1299.99,
        "totalRevenue": 3899.97,
        "customerType": "B2B",
        "customerName": "Hosting Provider"
    },
    {
        "date": "22-07-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 28,
        "unitPrice": 199.99,
        "totalRevenue": 5599.72,
        "customerType": "B2B",
        "customerName": "Compliance Software Co"
    },
    {
        "date": "25-07-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 15,
        "unitPrice": 299.99,
        "totalRevenue": 4499.85,
        "customerType": "B2B",
        "customerName": "Customer Service Co"
    },
    {
        "date": "28-07-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Consulting",
        "productName": "Training Package",
        "quantity": 5,
        "unitPrice": 999.99,
        "totalRevenue": 4999.95,
        "customerType": "B2B",
        "customerName": "Professional Services"
    },
    {
        "date": "02-08-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 18,
        "unitPrice": 599.99,
        "totalRevenue": 10799.82,
        "customerType": "B2B",
        "customerName": "Business Analytics Co"
    },
    {
        "date": "05-08-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 9,
        "unitPrice": 899.99,
        "totalRevenue": 8099.91,
        "customerType": "B2B",
        "customerName": "Content Creation Co"
    },
    {
        "date": "08-08-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 32,
        "unitPrice": 299.99,
        "totalRevenue": 9599.68,
        "customerType": "B2B",
        "customerName": "Sales Platform"
    },
    {
        "date": "12-08-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 25,
        "unitPrice": 199.99,
        "totalRevenue": 4999.75,
        "customerType": "B2B",
        "customerName": "Privacy Solutions Co"
    },
    {
        "date": "15-08-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Strategy Consulting",
        "quantity": 2,
        "unitPrice": 4999.99,
        "totalRevenue": 9999.98,
        "customerType": "B2B",
        "customerName": "Strategic Consulting"
    },
    {
        "date": "18-08-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 6,
        "unitPrice": 1299.99,
        "totalRevenue": 7799.94,
        "customerType": "B2B",
        "customerName": "Infrastructure Co"
    },
    {
        "date": "22-08-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 23,
        "unitPrice": 599.99,
        "totalRevenue": 13799.77,
        "customerType": "B2B",
        "customerName": "Intelligence Platform"
    },
    {
        "date": "25-08-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 26,
        "unitPrice": 299.99,
        "totalRevenue": 7799.74,
        "customerType": "B2B",
        "customerName": "Customer Platform"
    },
    {
        "date": "28-08-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 31,
        "unitPrice": 199.99,
        "totalRevenue": 6199.69,
        "customerType": "B2B",
        "customerName": "Enterprise Security"
    },
    {
        "date": "02-09-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 4,
        "unitPrice": 899.99,
        "totalRevenue": 3599.96,
        "customerType": "B2C",
        "customerName": "Individual Customer"
    },
    {
        "date": "05-09-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 3,
        "unitPrice": 2499.99,
        "totalRevenue": 7499.97,
        "customerType": "B2B",
        "customerName": "Implementation Co"
    },
    {
        "date": "08-09-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 19,
        "unitPrice": 599.99,
        "totalRevenue": 11399.81,
        "customerType": "B2B",
        "customerName": "Insights Company"
    },
    {
        "date": "12-09-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 21,
        "unitPrice": 299.99,
        "totalRevenue": 6299.79,
        "customerType": "B2B",
        "customerName": "Relationship Management Co"
    },
    {
        "date": "15-09-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 27,
        "unitPrice": 199.99,
        "totalRevenue": 5399.73,
        "customerType": "B2B",
        "customerName": "Protection Services"
    },
    {
        "date": "18-09-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 2,
        "unitPrice": 1299.99,
        "totalRevenue": 2599.98,
        "customerType": "B2B",
        "customerName": "Server Solutions Co"
    },
    {
        "date": "22-09-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Training Package",
        "quantity": 7,
        "unitPrice": 999.99,
        "totalRevenue": 6999.93,
        "customerType": "B2B",
        "customerName": "Education Platform"
    },
    {
        "date": "25-09-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 25,
        "unitPrice": 599.99,
        "totalRevenue": 14999.75,
        "customerType": "B2B",
        "customerName": "Advanced Analytics Co"
    },
    {
        "date": "28-09-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 29,
        "unitPrice": 299.99,
        "totalRevenue": 8699.71,
        "customerType": "B2B",
        "customerName": "Customer Experience Co"
    },
    {
        "date": "02-10-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 6,
        "unitPrice": 899.99,
        "totalRevenue": 5399.94,
        "customerType": "B2B",
        "customerName": "Creative Solutions Co"
    },
    {
        "date": "05-10-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 33,
        "unitPrice": 199.99,
        "totalRevenue": 6599.67,
        "customerType": "B2B",
        "customerName": "Cyber Defense Co"
    },
    {
        "date": "08-10-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 35,
        "unitPrice": 299.99,
        "totalRevenue": 10499.65,
        "customerType": "B2B",
        "customerName": "Engagement Platform"
    },
    {
        "date": "12-10-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Consulting",
        "productName": "Strategy Consulting",
        "quantity": 3,
        "unitPrice": 4999.99,
        "totalRevenue": 14999.97,
        "customerType": "B2B",
        "customerName": "Strategy Partners"
    },
    {
        "date": "15-10-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 22,
        "unitPrice": 599.99,
        "totalRevenue": 13199.78,
        "customerType": "B2B",
        "customerName": "Decision Intelligence Co"
    },
    {
        "date": "18-10-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 4,
        "unitPrice": 1299.99,
        "totalRevenue": 5199.96,
        "customerType": "B2B",
        "customerName": "Computing Solutions"
    },
    {
        "date": "22-10-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 29,
        "unitPrice": 199.99,
        "totalRevenue": 5799.71,
        "customerType": "B2B",
        "customerName": "Security Intelligence Co"
    },
    {
        "date": "25-10-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 31,
        "unitPrice": 299.99,
        "totalRevenue": 9299.69,
        "customerType": "B2B",
        "customerName": "Revenue Operations Co"
    },
    {
        "date": "28-10-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 2,
        "unitPrice": 2499.99,
        "totalRevenue": 4999.98,
        "customerType": "B2B",
        "customerName": "Systems Integration Co"
    },
    {
        "date": "02-11-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 27,
        "unitPrice": 599.99,
        "totalRevenue": 16199.73,
        "customerType": "B2B",
        "customerName": "Predictive Analytics Co"
    },
    {
        "date": "05-11-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 10,
        "unitPrice": 899.99,
        "totalRevenue": 8999.9,
        "customerType": "B2B",
        "customerName": "Production Studio"
    },
    {
        "date": "08-11-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 36,
        "unitPrice": 199.99,
        "totalRevenue": 7199.64,
        "customerType": "B2B",
        "customerName": "Risk Management Co"
    },
    {
        "date": "12-11-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 38,
        "unitPrice": 299.99,
        "totalRevenue": 11399.62,
        "customerType": "B2B",
        "customerName": "Customer Intelligence Co"
    },
    {
        "date": "15-11-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Consulting",
        "productName": "Training Package",
        "quantity": 8,
        "unitPrice": 999.99,
        "totalRevenue": 7999.92,
        "customerType": "B2B",
        "customerName": "Skills Development Co"
    },
    {
        "date": "18-11-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 24,
        "unitPrice": 599.99,
        "totalRevenue": 14399.76,
        "customerType": "B2B",
        "customerName": "Performance Analytics Co"
    },
    {
        "date": "22-11-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 7,
        "unitPrice": 1299.99,
        "totalRevenue": 9099.93,
        "customerType": "B2B",
        "customerName": "Enterprise Infrastructure Co"
    },
    {
        "date": "25-11-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 32,
        "unitPrice": 199.99,
        "totalRevenue": 6399.68,
        "customerType": "B2B",
        "customerName": "Threat Protection Co"
    },
    {
        "date": "28-11-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 34,
        "unitPrice": 299.99,
        "totalRevenue": 10199.66,
        "customerType": "B2B",
        "customerName": "Customer Success Platform"
    },
    {
        "date": "02-12-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Consulting",
        "productName": "Strategy Consulting",
        "quantity": 4,
        "unitPrice": 4999.99,
        "totalRevenue": 19999.96,
        "customerType": "B2B",
        "customerName": "Transformation Partners"
    },
    {
        "date": "05-12-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 30,
        "unitPrice": 599.99,
        "totalRevenue": 17999.7,
        "customerType": "B2B",
        "customerName": "Data Insights Co"
    },
    {
        "date": "08-12-2024",
        "salesRep": "James Wilson",
        "region": "Europe",
        "productCategory": "Hardware",
        "productName": "Workstation Elite",
        "quantity": 5,
        "unitPrice": 899.99,
        "totalRevenue": 4499.95,
        "customerType": "B2C",
        "customerName": "Individual Customer"
    },
    {
        "date": "12-12-2024",
        "salesRep": "Sarah Johnson",
        "region": "North America",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 40,
        "unitPrice": 199.99,
        "totalRevenue": 7999.6,
        "customerType": "B2B",
        "customerName": "Compliance Automation Co"
    },
    {
        "date": "15-12-2024",
        "salesRep": "Ana Martinez",
        "region": "South America",
        "productCategory": "Software",
        "productName": "CRM Pro",
        "quantity": 25,
        "unitPrice": 299.99,
        "totalRevenue": 7499.75,
        "customerType": "B2B",
        "customerName": "Sales Acceleration Co"
    },
    {
        "date": "18-12-2024",
        "salesRep": "Michael Chen",
        "region": "Asia Pacific",
        "productCategory": "Consulting",
        "productName": "Implementation Service",
        "quantity": 5,
        "unitPrice": 2499.99,
        "totalRevenue": 12499.95,
        "customerType": "B2B",
        "customerName": "Digital Solutions Co"
    },
    {
        "date": "22-12-2024",
        "salesRep": "Emily Rodriguez",
        "region": "Europe",
        "productCategory": "Software",
        "productName": "Analytics Suite",
        "quantity": 28,
        "unitPrice": 599.99,
        "totalRevenue": 16799.72,
        "customerType": "B2B",
        "customerName": "Strategic Intelligence Co"
    },
    {
        "date": "25-12-2024",
        "salesRep": "David Thompson",
        "region": "North America",
        "productCategory": "Hardware",
        "productName": "Server Rack X1",
        "quantity": 8,
        "unitPrice": 1299.99,
        "totalRevenue": 10399.92,
        "customerType": "B2B",
        "customerName": "Infrastructure Solutions Co"
    },
    {
        "date": "28-12-2024",
        "salesRep": "Lisa Wang",
        "region": "Asia Pacific",
        "productCategory": "Software",
        "productName": "Security Shield",
        "quantity": 38,
        "unitPrice": 199.99,
        "totalRevenue": 7599.62,
        "customerType": "B2B",
        "customerName": "Cybersecurity Platform"
    }
]

export default SampleData;